const
DAY1=1000*60*60*24,
DAYS=['Sun','Mon','Tue','Wed','Thu','Fri','Sat'],
MONTHS=['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'],
timeChecker=new RegExp(/^(0?[1-9]|1[012])[:\.]([0-5]\d)[ap]m$/),
spaceRM=new RegExp(/\s+/g,''),
timeSplit=new RegExp(/[:\.]/),
pObj=pico.export('pico/obj'),
fb=require('api/fbJSON'),
rdAction=require('redis/action'),
rdTrip=require('redis/trip')

return {
	setup(context,cb){
		cb()
	},
	askDate(user,msg,next){
		const
		replies=[],
		now=Date.now()

		for(let i=0,t,d; i<7; i++){
			t=now+DAY1*i
			d=new Date(t)
			replies.push(fb.quickTextReply(`${DAYS[d.getDay()]}:${d.getDate()}/${MONTHS[d.getMonth()]}/${d.getFullYear()}`,d.toLocaleDateString()))
		}
		Object.assign(msg, fb.message(
			user,
			fb.text(
				'Add trip on which date?',
				replies
			)
		))
		next()
	},
	addDate(user,action,evt,next){
		const payload=pObj.dotchain(evt,['message','quick_reply','payload'])

		if(!payload) return next(null,'fb/askTripDate')
		action.pop()
		action.push('-',payload)
		next()
	},
	//askTime generated by createMsg
	addTime(user,action,evt,next){
		const text=pObj.dotchain(evt,['message','text'])

		if(!text) return next(null,'fb/askTripTime')
		const txt=text.toLowerCase().replace(spaceRM, '')
		if (!timeChecker.test(txt)) return next(null,'fb/askTripTime')
		const add='p'===txt.charAt(txt.length-2)?12:0
		const [hr,min]=txt.slice(0,-2).split(timeSplit)
		action.pop()
		action.push('+@date', (parseInt(hr)+add)+':'+min)
		next()
	},
	addPickup(user,action,evt,name,next){
		const text=pObj.dotchain(evt,['message','text'])

		if(!text) return next(null,`fb/ask${action[action.length-1]}`)
		const a=action.pop()
		switch(a){
		case 'TripFirstPickup':
			switch(text.toLowerCase()){
			case 'done': return next(null,`fb/ask${a}`)
			default:
				action.push('-',text)
				this.set(name,'TripPickup')
				break
			}
			break
		case 'TripPickup':
			switch(text.toLowerCase()){
			case 'done':
				action.push('+:pickup',null)
				this.set(name,'TripFirstDropoff')
				break
			default:
				action.push('-',text)
				this.set(name,'TripPickup')
				break
			}
			break
		default: return next(null,`fb/ask${a}`)
		}
		next()
	},
	addDropoff(user,action,evt,name,next){
		const text=pObj.dotchain(evt,['message','text'])

		if(!text) return next(null,`fb/ask${action[action.length-1]}`)
		const a=action.pop()
		switch(a){
		case 'TripFirstDropoff':
			switch(text.toLowerCase()){
			case 'done': return next(null,`fb/ask${a}`)
			default:
				action.push('-',text)
				this.set(name,'TripDropoff')
				break
			}
			break
		case 'TripDropoff':
			switch(text.toLowerCase()){
			case 'done':
				action.push('+:dropoff',null)
				this.set(name,'TripSeat')
				break
			default:
				action.push('-',text)
				this.set(name,'TripDropoff')
				break
			}
			break
		default: return next(null,`fb/ask${a}`)
		}
		next()
	},
	done(user,cmd,msg,next){
console.log('addTrp.done',user,cmd)
		rdTrip.set(user,cmd,(err)=>{
			if (err) Object.assign(msg, fb.message(user,fb.text(`An error has encountered when adding your trip: ${err}.\ntype help for more action`)))
			else Object.assign(msg, fb.message(user,fb.text(`New trip on ${(new Date(cmd.date)).toLocaleString()} has been added.\ntype help for more action`)))
			next()
		})
	}
}
